name: Publish Docker Image

on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yml

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image tag environment variable
      id: set-image-tag
      run: |
        if [ "${{ github.ref_type }}" = "branch" ]; then
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        fi

    - name: Set lower-case repository owner
      id: set-owner
      run: echo "LOWER_REPOSITORY_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build & push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.LOWER_REPOSITORY_OWNER }}/pmai:${{ env.IMAGE_TAG }}
          ghcr.io/${{ env.LOWER_REPOSITORY_OWNER }}/pmai:latest

